version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=donuts
      - MYSQL_USER=splitdemo
      - MYSQL_PASSWORD=splitdemo
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: ./
    restart: on-failure
    depends_on:
      - db
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.datasource.url" : "jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}",
      "spring.datasource.username" : "${DATABASE_USER}",
      "spring.datasource.password" : "${DATABASE_PASSWORD}",
      "spring.jpa.hibernate.ddl-auto": "update"
      }'
volumes:
  db-data: