version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=donuts
      - MYSQL_USER=splitdemo
      - MYSQL_PASSWORD=splitdemo
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql


  app:
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    command:
      - "/wait-for-it.sh db:3306 -- java -jar target/movie-service-0.0.1-SNAPSHOT.jar"
volumes:
  db-data: